# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/datastarlette',
                'doc_host': 'https://Deufel.github.io',
                'git_url': 'https://github.com/Deufel/datastarlette',
                'lib_path': 'datastarlette'},
  'syms': {'datastarlette.core': {'datastarlette.core.foo': ('core.html#foo', 'datastarlette/core.py')}}}
